-- Reconciled representation of the remote 20260923225648 migration.
-- This keeps the pre-existing private Tony memory tables reproducible locally.
create table if not exists public.tony_conversations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now(),
  search_vector tsvector generated always as (to_tsvector('portuguese',coalesce(content,''))) stored
);

create table if not exists public.tony_memories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  category text not null default 'general',
  content text not null,
  importance smallint not null default 5 check (importance between 1 and 10),
  source text not null default 'telegram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_vector tsvector generated always as (to_tsvector('portuguese',coalesce(content,''))) stored
);

create index if not exists tony_conversations_search_idx on public.tony_conversations using gin(search_vector);
create index if not exists tony_conversations_user_created_idx on public.tony_conversations(user_id,created_at desc);
create index if not exists tony_memories_search_idx on public.tony_memories using gin(search_vector);
create index if not exists tony_memories_user_importance_idx on public.tony_memories(user_id,importance desc,updated_at desc);
alter table public.tony_conversations enable row level security;
alter table public.tony_memories enable row level security;
revoke all on public.tony_conversations,public.tony_memories from public,anon,authenticated;
grant all on public.tony_conversations,public.tony_memories to service_role;
grant usage,select on sequence public.tony_conversations_id_seq,public.tony_memories_id_seq to service_role;
